opencti:
  replicas: 2
  resources:
    requests:
      memory: 4Gi
      cpu: "2"
    limits:
      memory: 8Gi
  worker:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
