apiVersion: v2
name: azul-minio
description: MinIO instance for Azul object storage
version: 0.1.0
type: application

dependencies:
  - name: minio
    version: 5.3.0
    repository: https://charts.min.io/
