## RKE2 profile: Longhorn storage, HPA enabled, higher resources, full plugins

storageClassName: longhorn

restapi:
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      memory: 4Gi
      cpu: "1"
    limits:
      memory: 8Gi
      cpu: "2"

plugins:
  yara-x:
    type: yara-x
    enabled: true
  maco:
    type: maco
    enabled: true
  suricata:
    type: suricata
    enabled: true
  generic:
    type: standard
    enabled: true
  virustotal:
    type: standard
    enabled: true
