{{- if .Values.apps.mobsf }}
{{ include "cti-stack.application" (dict
  "name" "cti-mobsf-postgresql"
  "wave" "4"
  "namespace" .Values.namespaces.mobsf
  "chart" "charts/mobsf-postgresql"
  "context" $
) }}
{{- end }}
