{{- if .Values.apps.opencti }}
{{ include "cti-stack.application" (dict
  "name" "cti-opencti"
  "wave" "7"
  "namespace" .Values.namespaces.opencti
  "chart" "charts/opencti"
  "context" $
) }}
{{- end }}
