{{- if or .Values.apps.azul .Values.apps.opencti }}
{{ include "cti-stack.application" (dict
  "name" "cti-opensearch-operator"
  "wave" "3"
  "namespace" .Values.namespaces.infra
  "chart" "charts/opensearch-operator"
  "context" $
) }}
{{- end }}
