{{- if .Values.apps.opencti }}
{{ include "cti-stack.application" (dict
  "name" "cti-redis"
  "wave" "4"
  "namespace" .Values.namespaces.infra
  "chart" "charts/redis"
  "context" $
) }}
{{- end }}
