apiVersion: v1
kind: Secret
metadata:
  name: mobsf-credentials
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-postgresql-credentials
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  host: {{ .Values.secrets.postgresql.host | quote }}
  port: {{ .Values.secrets.postgresql.port | quote }}
  database: {{ .Values.secrets.postgresql.database | quote }}
  username: {{ .Values.secrets.postgresql.username | quote }}
  password: {{ .Values.secrets.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-oidc-credentials
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  issuer-url: {{ .Values.secrets.oidc.issuerUrl | quote }}
  client-id: {{ .Values.secrets.oidc.clientId | quote }}
  client-secret: {{ .Values.secrets.oidc.clientSecret | quote }}
