{{- if .Values.minio.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opencti-minio-tls
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: opencti-minio-tls
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - opencti-minio
    - "{{ .Release.Name }}-minio"
    - opencti-minio.{{ .Release.Namespace }}.svc
    - opencti-minio.{{ .Release.Namespace }}.svc.cluster.local
    - "{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc"
    - "{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: cti-ca-issuer
    kind: ClusterIssuer
{{- end }}
