{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cti-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        ## Allow from cti-opencti namespace
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cti-opencti
        ## Allow from cti-infra namespace (internal services)
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cti-infra
      ports:
        - port: 6379
          protocol: TCP
        - port: 6380
          protocol: TCP
  egress:
    ## Allow DNS
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
