apiVersion: v2
name: opensearch-operator
description: OpenSearch Kubernetes Operator for CTI Stack (operator only, no data)
version: 0.1.0
type: application

dependencies:
  - name: opensearch-operator
    version: 2.8.2
    repository: https://opensearch-project.github.io/opensearch-k8s-operator/
