apiVersion: v1
kind: Secret
metadata:
  name: opencti-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  admin-email: {{ .Values.secrets.admin.email | quote }}
  admin-password: {{ .Values.secrets.admin.password | quote }}
  admin-token: {{ .Values.secrets.admin.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-opensearch-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  url: {{ .Values.secrets.opensearch.url | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-rabbitmq-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  hostname: {{ .Values.secrets.rabbitmq.hostname | quote }}
  port: {{ .Values.secrets.rabbitmq.port | quote }}
  username: {{ .Values.secrets.rabbitmq.username | quote }}
  password: {{ .Values.secrets.rabbitmq.password | quote }}
  management-port: {{ .Values.secrets.rabbitmq.managementPort | quote }}
  ssl: {{ .Values.secrets.rabbitmq.ssl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-redis-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  hostname: {{ .Values.secrets.redis.hostname | quote }}
  port: {{ .Values.secrets.redis.port | quote }}
  password: {{ .Values.secrets.redis.password | quote }}
  ssl: {{ .Values.secrets.redis.ssl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-minio-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  endpoint: {{ .Values.secrets.minio.endpoint | quote }}
  port: {{ .Values.secrets.minio.port | quote }}
  access-key: {{ .Values.secrets.minio.accessKey | quote }}
  secret-key: {{ .Values.secrets.minio.secretKey | quote }}
  bucket: {{ .Values.secrets.minio.bucket | quote }}
  use-ssl: {{ .Values.secrets.minio.useSsl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-oidc-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  issuer-url: {{ .Values.secrets.oidc.issuerUrl | quote }}
  client-id: {{ .Values.secrets.oidc.clientId | quote }}
  client-secret: {{ .Values.secrets.oidc.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opencti-postgresql-credentials
  labels:
    app.kubernetes.io/name: opencti
    app.kubernetes.io/part-of: cti-stack
type: Opaque
stringData:
  host: {{ .Values.secrets.postgresql.host | quote }}
  port: {{ .Values.secrets.postgresql.port | quote }}
  database: {{ .Values.secrets.postgresql.database | quote }}
  username: {{ .Values.secrets.postgresql.username | quote }}
  password: {{ .Values.secrets.postgresql.password | quote }}
