apiVersion: batch/v1
kind: Job
metadata:
  name: azul-minio-create-buckets
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mc
          image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{- if .Values.minio.tls.enabled }}
              mc alias set myminio https://{{ .Release.Name }}-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD --insecure
              {{- range .Values.buckets }}
              mc mb --ignore-existing myminio/{{ .name }} --insecure
              {{- end }}
              {{- else }}
              mc alias set myminio http://{{ .Release.Name }}-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              {{- range .Values.buckets }}
              mc mb --ignore-existing myminio/{{ .name }}
              {{- end }}
              {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio
                  key: rootPassword
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: mc-config
              mountPath: /.mc
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: mc-config
          emptyDir:
            medium: Memory
