apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobsf.fullname" . }}-config
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  MOBSF_DB_TYPE: "postgres"
  MOBSF_ASYNC_ANALYSIS: "1"
