apiVersion: v1
kind: ServiceAccount
metadata:
  name: cti-mobsf
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cti-mobsf
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mobsf-credentials", "mobsf-postgresql-credentials"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cti-mobsf-config"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cti-mobsf
  labels:
    app.kubernetes.io/name: mobsf
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cti-mobsf
subjects:
  - kind: ServiceAccount
    name: cti-mobsf
